### ISSUE TITLE
Regression in Model Loading Performance After Context Length Update

### ISSUE THREAD

**Issue by emilnorsker** [nobodywho-ooo/nobodywho#46]
# Regression in Model Loading Performance After Context Length Update

## Description

After updating to **NobodyWho version 3.01**, which transitions away from a fixed context length, I`ve experienced significant losses in performance and limitations in the size of models I can run. Models that previously worked now fail to load or crash during execution. I believe this issue is related to increased memory requirements due to larger context lengths and batch sizes.

## System Specs

- **Operating System**: Windows 11
- **NobodyWho Version**: 3.01
- **GPU**: NVIDIA GeForce RTX 4060 Laptop GPU (8 GB VRAM)
- **RAM**: 32 GB

## Models Tested

I`ve tested several models with varying parameters. The results are summarized in the table below:

| Model Name                      | Context Size | Model Size | Batch Size | Contexts Initialized | Ran Successfully |
|---------------------------------|--------------|------------|------------|----------------------|------------------|
| `gemma-2-9b-it-GGUF`            | 8192         | 5.36 GiB   | 2048       | 1                    | No               |
| `gemma-2-2b-jpn-it-IQ4_XS.gguf` | 8192         | 1.45 GiB   | 2048       | 1                    | Yes              |
| `gemma-2-2b-jpn-it-IQ4_XS.gguf` | 8192         | 1.45 GiB   | 2048       | 4                    | No               |
| `gemma-2-2b-jpn-it-IQ4_XS.gguf` | 8192         | 1.45 GiB   | 2048       | 5                    | No               |
| `llama-3.2-3b-instruct-uncensored-q2_k`                   | 131072       | 1.38 GiB   | 2048       | 1                    | No               |

### Details and Logs

<details>
  <summary>Details and Logs</summary>

#### `gemma-2-9b-it-GGUF`

I was unable to load this model at all, even though it worked before the context length update.

- **Model Size**: 5.36 GiB
- **Embedding Size (`n_embd`)**: 3584
- **Number of Layers (`n_layer`)**: 42
- **Context Length (`n_ctx`)**: 8192
- **Batch Size (`n_batch`)**: 2048
- **Precision**: Assuming `fp16` (2 bytes)

**Relevant Logs:**

```

llm_load_print_meta: model size       = 5.36 GiB (4.98 BPW)
llm_load_tensors: NVIDIA GeForce RTX 4060 Laptop GPU buffer size =  5488.40 MiB
llm_load_tensors: CPU buffer size =   717.77 MiB
llama_new_context_with_model: n_ctx      = 8192
...
alloc_tensor_range: failed to allocate NVIDIA GeForce RTX 4060 Laptop GPU buffer of size 2818572288
llama_kv_cache_init: failed to allocate buffer for kv cache
llama_new_context_with_model: llama_kv_cache_init() failed for self-attention cache
fatal runtime error: Rust cannot catch foreign exceptions
```

#### `gemma-2-2b-jpn-it-IQ4_XS.gguf`

- **Model Size**: 1.45 GiB
- **Embedding Size (`n_embd`)**: 2304
- **Number of Layers (`n_layer`)**: 26
- **Context Length (`n_ctx`)**: 8192
- **Batch Size (`n_batch`)**: 2048
- **Precision**: Assuming `fp16` (2 bytes)

- With **1 context active**, the model loads successfully.

**Relevant Logs (1 Context):**

```

llama_new_context_with_model: n_ctx      = 8192
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
...
llama_kv_cache_init: NVIDIA GeForce RTX 4060 Laptop GPU KV buffer size =   832.00 MiB
llama_new_context_with_model: KV self size  =  832.00 MiB, K (f16):  416.00 MiB, V (f16):  416.00 MiB
```

- With **4 contexts active**, the application crashes.

**Relevant Logs (4 Contexts):**

```

...
llama_kv_cache_init: NVIDIA GeForce RTX 4060 Laptop GPU KV buffer size =   832.00 MiB
ERROR:             vkFreeMemory: Invalid device [VUID-vkFreeMemory-device-parameter]
```

- With **5 contexts active**, the application crashes immediately.

**Relevant Logs (5 Contexts):**

```

...
llama_kv_cache_init: NVIDIA GeForce RTX 4060 Laptop GPU KV buffer size =   832.00 MiB
ERROR:             vkFreeMemory: Invalid device [VUID-vkFreeMemory-device-parameter]
```

#### `llama 32 Q2`

Attempting to load this model results in an immediate crash due to memory allocation failures.

- **Model Size**: 1.38 GiB
- **Embedding Size (`n_embd`)**: 3072
- **Number of Layers (`n_layer`)**: 28
- **Context Length (`n_ctx`)**: 131072
- **Batch Size (`n_batch`)**: 2048
- **Precision**: Assuming `fp16` (2 bytes)

**Relevant Logs:**

```

...
llama_new_context_with_model: n_ctx      = 131072
llama_new_context_with_model: n_batch    = 2048
...
alloc_tensor_range: failed to allocate NVIDIA GeForce RTX 4060 Laptop GPU buffer of size 4026531840
llama_kv_cache_init: failed to allocate buffer for kv cache
llama_new_context_with_model: llama_kv_cache_init() failed for self-attention cache
fatal runtime error: Rust cannot catch foreign exceptions
```
</details>

## Conclusion

The increased context length and batch sizes in the latest version appear to significantly increase the memory requirements, leading to allocation failures and crashes. The calculations show that the total memory required by the models exceeds the available VRAM when using large context lengths or multiple contexts simultaneously. This regression affects the usability of models that previously worked under earlier versions of NobodyWho.

---

**Comment by AsbjornOlling** [comment]
Closed with #48
