### ISSUE TITLE
Duplicated callback after 4-5 messages

### ISSUE THREAD

**Issue by geowarin** [nobodywho-ooo/nobodywho#62]
Hey! Thanks for the lib, very funny to mess around with!

I tried to make a simple chat but after a few call to `say()`, I begin to receive more and more calls to the `response_finished` signal.

```gdscript
extends NobodyWhoChat

func _ready():
	# configure node
	model_node = get_node("../ChatModel")
	system_prompt = "You are an evil wizard. Always try to curse anyone who talks to you. Only talk, do not write descriptions or actions. Try to keep your answers short."

	%ChatInput.gui_input.connect(on_gui_input)
	response_finished.connect(on_response)
	start_worker()

func on_gui_input(event: InputEvent):
	if event is InputEventKey:
		if event.key_label == KEY_ENTER && event.pressed && !event.echo:
			var text: String = %ChatInput.text
			if text != "":
				%ChatText.text += "YOU: " + text + "\n"
				say(text)
				%ChatInput.text = ""
				%ChatInput.accept_event()

func on_response(response: String):
	%ChatText.text += response.replace("<end_of_turn>", "\n")
```

![image](https://github.com/user-attachments/assets/a7ed6804-6c08-47b8-b2c7-ceac8bfd94bf)

Which is pretty funny :smile: but makes the system hard to use!

**Comment by geowarin** [comment]
I'm also wondering where the `<end of turn>` string comes from?

**Comment by AsbjornOlling** [comment]
This is strange, but reproducible. I'm investigating :+1:

**Comment by AsbjornOlling** [comment]
You might just have been unlucky? :sweat_smile: 

I think that it actually isn't `response_finished` signal several times for each message, but just returning responses that consist of the same message several times in a row.

If I run the gemma 2 2b model with the same prompt and the same messages that you showed, I can also get it to produce messages that consist of the same thing over and over. If I change the sampler seed from 1234 to something else (e.g. 1337), I no longer get repetition. 

LLMs repeating themselves is a known problem. This is commonly addressed by penalizing repetition using the sampler. The idea is just to reduce the scores of tokens that have been chosen recently. You can do it by setting "Penalty Last N" and "Penalty Repeat" in the sampler. That should fix repetitions in the general case.

![image](https://github.com/user-attachments/assets/24c31fa9-d93d-4662-8a4a-6ca6a9671f2a)


Welcome to the weird world of LLMs.

**Comment by AsbjornOlling** [comment]
If you could verify that this is also what's happening for you (that it's generating repetitive responses, and not calling `response_finished` several times), that would be great :innocent:

**Comment by geowarin** [comment]
Playing with the parameters just makes the issue less reproducible (I still have some occurrences it seems).

I found [some documentation](https://github.com/ggerganov/llama.cpp/tree/master/examples/main#dry-repetition-penalty) about llama and repetition.

I know nothing about LLMs but isn't it a fair assumption that one prompt will produce one output?

Strange word indeed.

**Comment by AsbjornOlling** [comment]
> Playing with the parameters just makes the issue less reproducible (I still have some occurrences it seems).

But does applying repeat penalties work? Is it less likely to repeat itself, the greater the penalty?

> I found [some documentation](https://github.com/ggerganov/llama.cpp/tree/master/examples/main#dry-repetition-penalty) about llama and repetition.

NobodyWho doesn't support the DRY sampler from Llama.cpp yet. Right now, it will always use the mirostat v2 sampler (with optional penalties). More samplers are coming, though :sparkles: 

>  isn't it a fair assumption that one prompt will produce one output?

Yes and no. It is deterministic, but more things than the prompt affect the output. Given the same model, prompt, seed and sampler configuration, it will produce the same output. I suspect that is what you meant :innocent: 

> Strange word indeed 😆
